version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "03:24"
  target-branch: main
  labels:
    - CI/CD
    - skip-changelog
    - priority/low
  groups:
    github-actions:
      patterns:
        - "*"

- package-ecosystem: pip
  directories:
    - "/"
    - "/.github/utils"
  schedule:
    interval: weekly
    time: "03:16"
  target-branch: main
  labels:
    - CI/CD
    - skip-changelog
    - priority/low
  groups:
    python:
      applies-to: "version-updates"
      patterns:
        - "*"
    python-security:
      applies-to: "security-updates"
      patterns:
        - "*"
