name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  gitlab-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Install Twine
        run: python -m pip install twine

      - name: Publish release distributions to GitLab PyPI
        run: |
          twine upload \
            --repository-url https://gitlab.sintef.no/api/v4/projects/17883/packages/pypi \
            -u __token__ \
            -p "${{ secrets.CI_JOB_TOKEN }}" \
            dist/*
