name: CD - Release

on:
  release:
    types: [published]

jobs:
  build:
    name: External
    uses: SINTEF/ci-cd/.github/workflows/cd_release.yml@v2.9.2
    if: github.repository == 'SemanticMatter/mqttelemetry' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    with:
      # General
      # Use a GitHub-hosted runner here due to incompatibility between self-hosted runners and the
      # push-protected action
      runner: ubuntu-latest
      git_username: ${{ vars.CI_CD_GIT_USER }}
      git_email: ${{ vars.CI_CD_GIT_EMAIL }}
      release_branch: main
      system_dependencies: 'cmake make gcc g++ libssl-dev'

      # Python package
      python_package: true
      package_dirs: dataspaces_graphs
      pip_index_url: ${{ vars.GITLAB_PACKAGE_REGISTRY_URL }}/simple
      install_extras: "[dev]"
      python_version_build: "3.10"
      build_libs: flit
      build_cmd: "flit build"
      build_dir: "dist"
      changelog_exclude_labels: skip-changelog,duplicate,question,invalid,wontfix
      publish_on_pypi: false
      upload_distribution: true
      version_update_changes_separator: ","
      version_update_changes: |
        {package_dir}/__init__.py,__version__ *= *(?:'|\").*(?:'|\"),__version__ = \"{version}\"
        prepare_testing.sh,:pytest-.* --target,:pytest-{version} --target
        .github/workflows/ci_tests.yml,:pytest-.*,:pytest-{version}

      # Documentation
      update_docs: false

    secrets:
      PAT: ${{ secrets.SEMANTICMATTER_PAT }}

  publish:
    name: Publish to SINTEF GitLab
    needs: build
    # Use a GitHub-hosted runner here due to incompatibility between self-hosted runners and the
    # push-protected action
    runs-on: ubuntu-latest

    # environment:
    #   name: GitLab
    #   url: ${{ vars.GITLAB_PACKAGE_URL }}

    steps:
      - name: Download distribution
        uses: actions/download-artifact@v4
        with:
          name: dist  # The artifact will always be called 'dist'
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # The path to the distribution to upload
          packages-dir: dist
          repository-url: ${{ vars.GITLAB_PACKAGE_REGISTRY_URL }}
          user: ${{ secrets.DEPLOY_TOKEN_USERNAME }}
          password: ${{ secrets.DEPLOY_TOKEN_PASSWORD }}

      - name: Summary
        run: |
          echo "Published to SemanticMatter @ SINTEF GitLab"
          echo "See package at: ${{ vars.GITLAB_PACKAGE_URL }}"
